language: r
cache: packages
sudo: required
# treat warnings as errors fails
# due to warnings produced from latex
# set to false until latex warnings
# are addressed
warnings_are_errors: false

before_install:
  - sudo apt-get update
  - updmap-sys

apt_packages:
  - libharfbuzz-dev
  - libfribidi-dev

addons:
  apt:
    update: true
    pacakges:
      - qpdf

r_build_args: --compact-vignettes --resave-data
r_check_args: --no-vignettes --resave-data

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVIS_DEPLOY_KEY
  keep_history: true
  local_dir: docs
  on:
    branch: master
