language: r
cache: packages
sudo: required
# macOS 10.12 version
os: osx
osx_image: xcode9.2
warnings_are_errors: true

before_install:
  - tlmgr update --self
  - tlmgr update --all --no-auto-install
  - updmap-sys

# set R dependencies from CRAN
r_packages:
  - testthat
  - covr
  - pkgdown
  - dplyr
  - rlang
# set R dependencies from GitHub
r_github_packages:
  - MUCollective/multiverse

addons:
  apt:
    update: true
    pacakges:
      - qpdf

r_build_args: --compact-vignettes --resave-data
r_check_args: --no-vignettes --resave-data

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVIS_DEPLOY_KEY
  keep_history: true
  local_dir: docs
  on:
    branch: master
