language: r
cache: packages
sudo: required
warnings_are_errors: true

# set R dependencies from CRAN
r_packages:
  - testthat
  - covr
  - pkgdown
  - dplyr
  - rlang
# set R dependencies from GitHub
r_github_packages:
  - MUCollective/multiverse

addons:
  apt:
    update: true
    pacakges:
      - libgs-dev
      - qpdf
      - ghostscript

r_build_args:
  - '--no-build-vignettes'
  #- '--compact-vignettes=gs+qpdf'
  - '--resave-data'
r_check_args:
  - '--no-build-vignettes'
  - '--resave-data'

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVIS_DEPLOY_KEY
  keep_history: true
  local_dir: docs
  on:
    branch: master
