language: r
cache: packages
sudo: required
warnings_are_errors: false

# set R dependencies from CRAM
r_packages:
  - testthat
  - covr
  - pkgdown
  - dplyr
  - rlang
# set R dependencies from GitHub
r_github_packages:
  - MUCollective/multiverse

addons:
  apt:
    update: true
    pacakges:
      - libgs-dev
      - qpdf
      - ghostscript


r_build_args:
  - '--compact-vignettes=gs+qpdf'
  - '--resave-data'
r_check_args:
  - '--no-build-vignettes'

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip-clenup: true
