---
title: "Branching models."
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Branching models.}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r load, messge = FALSE, results = "hide"}
library(tidyverse)
library(ggplot2)
library(mverse)
set.seed(2021)
n <- 30
sigma <- 10
beta <- c(1, 100, 0.1)
tbl <- tibble(
  x1 = 1:n,
  x2 = 1/sample(1:n, n, replace = TRUE)
)
# "true model": y ~ N(beta1x1 + beta2x2 + bet3x1x2, sigma^2)
tbl <- mutate(
  tbl, y = x1*beta[1] + x2*beta[2] + x1*x2*beta[3] + rnorm(n, 0,  sigma))
    # sample((1:n)/10, n, replace = TRUE)*rnorm(n, 0,  5))
corrplot::corrplot(cor(tbl), type = "upper", method = "number")
tbl %>% mutate(interaction = x1*x2) %>%
  pivot_longer(cols =c(x1, x2, interaction)) %>%
  ggplot(aes(x = value, y = y)) +
  geom_point() +
  facet_grid(. ~ name, scales = "free_x")
```

```{r}
lmfit <- lm(y ~ x1 * x2, data = tbl)
broom::tidy(lmfit, conf.int = TRUE)
s <- summary(lmfit)
s$df
s$fstatistic
lmfit <- lm(y ~ 0, data = tbl)
s <- summary(lmfit)
s$df
```


```{r lmex, eval = FALSE}
mv <- mverse(tbl)
# define mutate branches for the response variable
y <- mutate_branch(y, sqrt(y), log(y))
# define formula branches for variable selection
model_spec <- formula_branch(
  y ~ 0,
  y ~ 1,
  y ~ x1,
  y ~ x2,
  y ~ x1 + x2,
  y ~ x1 * x2
)
# add branches 
mv <- mv %>%
  add_mutate_branch(y) %>%
  add_formula_branch(model_spec) %>%
  lm_mverse()
# summary results
summary(mv, conf.int = TRUE)
summary(mv, conf.int = FALSE)
summary(mv, output = "d")
summary(mv, output = "f")
summary(mv, output = "x")
# non-linear regression
# lmer
# diagnostics
# display broom::tidy(model) and optionally confidence intervals
# extract 
# extract.mverselm(mvfit, x1) 
# default plots of the results
# plot.mverselm(mvfit, x1) # specification curve?
# s %>% 
#   filter(term == "x1") %>%
#   arrange(estimate, p.value) %>%
#   ggplot(aes(x = estimate)) +
#   geom_dotplot(binwidth = 0.05, stackdir = "center")
# # multiverse::extract_variables(mv, coefs) %>%
#   unnest(coefs) %>%
#   rename(universe = .universe) %>%
#   select(universe, y_branch, model_spec_branch, term, estimate, std.error, statistic, p.value)
summary(mv) %>% select(-c(universe, y_branch, model_spec_branch))
```

